version: "3"
services:
  postgrescontacts:
    image: postgres
    container_name: postgrescontacts
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dev_admin
      POSTGRES_DB: contactsdb
    networks:
      - netnpx
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "contactsdb", "-U", "dev_admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: bncc111/backend
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgrescontacts:
        condition: service_healthy
    networks:
      - netnpx

  react:
    image: bncc111/react
    container_name: react
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      postgrescontacts:
        condition: service_healthy
    networks:
      - netnpx

volumes:
  db-data:

networks:
  netnpx:
    driver: bridge
